### PR TITLE
Inital html in main handlebars file

### PR DESCRIPTION
**Pull request by tugwellchristi**
Review initial content in main.handlebars. Includes nav bar and header.

### CODE REVIEW

**Review by VictoriaSweet — COMMENTED** [review]
Did you mean to put " If thIde plant is edible" ? Lol other than that it looks golden to me

**Comment by tugwellchristi** [comment]
> Did you mean to put " If thIde plant is edible" ? Lol other than that it looks golden to me

Sometimes words are hard. Lol. Thanks for catching that!

**Review by VictoriaSweet — CHANGES_REQUESTED** [review]
edit line 8 in README.md

**Review by VictoriaSweet — APPROVED** [review]

**Review by Deazymat — APPROVED** [review]
yeee

**Pull request merged**
